FROM apache/superset:latest

USER root

RUN pip install --upgrade pip && \
    pip install apache-superset[trino] --upgrade && \
    pip install pyhive hive && \
    pip install pyiceberg && \
    pip install openmetadata-sqlalchemy-hive \
    pip install psycopg2 \
    pip install psycopg2-binary

COPY ./superset_init.sh /app/superset_init.sh

RUN chmod +x /app/superset_init.sh

USER superset

ENTRYPOINT ["/app/superset_init.sh"]
